=== ppwgit/armyproject/src/main/java/com/solvd/lab/army/xml/soldiers.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="soldiers">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="soldier" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="id" type="xs:long"/>
                            <xs:element name="firstName" type="xs:string"/>
                            <xs:element name="lastName" type="xs:string"/>
                            <xs:element name="dateOfBirth" type="xs:date"/>
                            <xs:element name="gender" type="xs:string"/>
                            <xs:element name="contactNumber" type="xs:string"/>
                            <xs:element name="emergencyNumber" type="xs:string"/>
                            <xs:element name="email" type="xs:string"/>
                            <xs:element name="address" type="xs:string"/>
                            <xs:element name="rankId" type="xs:long"/>
                            <xs:element name="roleId" type="xs:long"/>
                            <xs:element name="baseId" type="xs:long"/>
                            <xs:element name="serviceStatus" type="xs:string"/>
                            <xs:element name="soldierStatus" type="xs:string"/>
                            <xs:element name="rank" type="xs:string"/>
                            <xs:element name="role" type="xs:string"/>
                            <xs:element name="base" type="xs:string"/>
                            <xs:element name="skills">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="skill" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="id" type="xs:long"/>
                                                    <xs:element name="name" type="xs:string"/>
                                                    <xs:element name="description" type="xs:string"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="operations">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="operation" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="id" type="xs:long"/>
                                                    <xs:element name="name" type="xs:string"/>
                                                    <xs:element name="startDate" type="xs:date"/>
                                                    <xs:element name="endDate" type="xs:date"/>
                                                    <xs:element name="location" type="xs:string"/>
                                                    <xs:element name="operationTypeId" type="xs:long"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="operationType" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="id" type="xs:long"/>
                                                    <xs:element name="name" type="xs:string"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="units">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="unit" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="id" type="xs:long"/>
                                                    <xs:element name="name" type="xs:string"/>
                                                    <xs:element name="unitType" type="xs:string"/>
                                                    <xs:element name="soldierId" type="xs:long"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== ppwgit/armyproject/src/main/java/com/solvd/lab/army/xml/soldiers.xml
<soldiers xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:noNamespaceSchemaLocation="soldiers.xsd">
    <soldier>
        <id>1</id>
        <firstName>Ava</firstName>
        <lastName>SimpleLastname</lastName>
        <dateOfBirth>1990-01-01</dateOfBirth>
        <gender>Male</gender>
        <contactNumber>1234567890</contactNumber>
        <emergencyNumber>9876543210</emergencyNumber>
        <email>abc@email.com</email>
        <address>123 Main Street</address>
        <rankId>1</rankId>
        <roleId>2</roleId>
        <baseId>3</baseId>
        <serviceStatus>Active</serviceStatus>
        <soldierStatus>On Duty</soldierStatus>
        <rank>Private</rank>
        <role>Infantry</role>
        <base>Base 1</base>
        <skills>
            <skill>
                <id>1</id>
                <name>Combat</name>
                <description>Combat AAA </description>
            </skill>
            <skill>
                <id>2</id>
                <name>First-Aid</name>
                <description>First-Aid des </description>
            </skill>
        </skills>
        <operations>
            <operation>
                <id>1</id>
                <name>Search and Rescue</name>
                <startDate>2025-12-11</startDate>
                <endDate>2020-12-11</endDate>
                <location>Bangkok</location>
                <operationTypeId>1</operationTypeId>
            </operation>
            <operationType>
                <id>1</id>
                <name>Protect</name>
            </operationType>
        </operations>
        <units>
            <unit>
                <id>1</id>
                <name>Division</name>
                <unitType>Infantry</unitType>
                <soldierId>1</soldierId>
            </unit>
            <unit>
                <id>1</id>
                <name>Army</name>
                <unitType>Infantry</unitType>
                <soldierId>1</soldierId>
            </unit>
        </units>
    </soldier>
</soldiers>
